apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.configMapName" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ if .Values.redis.enabled }}{{ include "url-shortener.redisName" . | quote }}{{ else }}{{ .Values.redis.host | quote }}{{ end }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIRECT_BASE_URL: {{ .Values.redirectBaseUrl | quote }}
