apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.shortenerName" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app: shortener
spec:
  replicas: {{ .Values.shortener.replicaCount }}
  selector:
    matchLabels:
      {{- include "url-shortener.selectorLabels" . | nindent 6 }}
      app: shortener
  template:
    metadata:
      labels:
        {{- include "url-shortener.selectorLabels" . | nindent 8 }}
        app: shortener
    spec:
      containers:
        - name: shortener
          image: "{{ .Values.shortener.image.repository }}:{{ .Values.shortener.image.tag }}"
          imagePullPolicy: {{ .Values.shortener.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.shortener.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "url-shortener.configMapName" . }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.shortener.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.shortener.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.shortener.resources | nindent 12 }}
      {{- with .Values.shortener.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shortener.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shortener.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
