apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shortener
spec:
  selector:
    matchLabels:
      app: shortener
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
